

// **************************************************
// File generated by: neuroConstruct v1.7.0 
// **************************************************

// This file holds the implementation in GENESIS of the Cell Mechanism:
// KDR_Hippo_ChannelML (Type: Channel mechanism, Model: ChannelML based process)

// with parameters: 
// /channelml/@units = SI Units 
// /channelml/notes = ChannelML file containing a single Channel description 
// /channelml/channel_type/@name = KDR_Hippo_ChannelML 
// /channelml/channel_type/status/@value = stable 
// /channelml/channel_type/status/comment = Equations fromM. C. Vanier and J. M. Bower, A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neural Models 
// /channelml/channel_type/status/contributor/name = Simon O'Connor 
// /channelml/channel_type/notes = Simple example of K conductance in M. C. Vanier and J. M. Bower, A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neura ... 
// /channelml/channel_type/authorList/modelTranslator/name = Simon O'Connor 
// /channelml/channel_type/authorList/modelTranslator/institution = Cardiff University 
// /channelml/channel_type/authorList/modelTranslator/email = simon.oconnor - at - btinternet.com 
// /channelml/channel_type/publication/fullTitle = M. C. Vanier and J. M. Bower, A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neural Models, . 
// /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=pubmed&amp;dopt=Abstract&amp;list_uids=12991237 
// /channelml/channel_type/neuronDBref/modelName = K channels 
// /channelml/channel_type/neuronDBref/uri = http://senselab.med.yale.edu/senselab/NeuronDB/channelGene2.htm#table3 
// /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
// /channelml/channel_type/current_voltage_relation/@ion = k 
// /channelml/channel_type/current_voltage_relation/@default_gmax = 270 
// /channelml/channel_type/current_voltage_relation/@default_erev = -0.075 
// /channelml/channel_type/current_voltage_relation/gate/@name = n 
// /channelml/channel_type/current_voltage_relation/gate/@instances = 1 
// /channelml/channel_type/current_voltage_relation/gate/closed_state/@id = n0 
// /channelml/channel_type/current_voltage_relation/gate/open_state/@id = n 
// /channelml/channel_type/current_voltage_relation/gate/transition[1]/@name = alpha 
// /channelml/channel_type/current_voltage_relation/gate/transition[1]/@from = n0 
// /channelml/channel_type/current_voltage_relation/gate/transition[1]/@to = n 
// /channelml/channel_type/current_voltage_relation/gate/transition[1]/@expr_form = generic 
// /channelml/channel_type/current_voltage_relation/gate/transition[1]/@expr = (v + 0.0392) &lt; 1e-6 &amp;&amp; (-v-0.0392) &lt; 1e-6? 79.4679 : ((-1.0 * 627.2) + (-1.0 * 16000 * v))/(-1.0 + (exp (-1.0 * (v + 0.0392)/ 0.005))) 
// /channelml/channel_type/current_voltage_relation/gate/transition[2]/@name = beta 
// /channelml/channel_type/current_voltage_relation/gate/transition[2]/@from = n 
// /channelml/channel_type/current_voltage_relation/gate/transition[2]/@to = n0 
// /channelml/channel_type/current_voltage_relation/gate/transition[2]/@expr_form = generic 
// /channelml/channel_type/current_voltage_relation/gate/transition[2]/@expr = 250.0 /(exp ((v + 0.0543)/ 0.04)) 
// /channelml/channel_type/impl_prefs/table_settings/@max_v = 0.1 
// /channelml/channel_type/impl_prefs/table_settings/@min_v = -0.1 
// /channelml/channel_type/impl_prefs/table_settings/@table_divisions = 3000 

// File from which this was generated: /home/padraig/git/PiriformCortexPyramidalNeuron/neuroConstruct/cellMechanisms/KDR_Hippo_ChannelML/KChannel_HH.xml

// XSL file with mapping to simulator: /home/padraig/git/PiriformCortexPyramidalNeuron/neuroConstruct/cellMechanisms/KDR_Hippo_ChannelML/ChannelML_v1.8.1_GENESIStab.xsl



// This is a GENESIS script file generated from a ChannelML v1.8.1 file
// The ChannelML file is mapped onto a tabchannel object


// Units of ChannelML file: SI Units, units of GENESIS file generated: SI Units

/*
    ChannelML file containing a single Channel description
*/

function make_KDR_Hippo_ChannelML

        /*
            Simple example of K conductance in M. C. Vanier and J. M. Bower, A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neural Models

            
Reference: M. C. Vanier and J. M. Bower, A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neural Models, .
            Pubmed: http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12991237

        */
        

        str chanpath = "/library/KDR_Hippo_ChannelML"

        if ({exists {chanpath}})
            return
        end
        
        create tabchannel {chanpath}
            

        setfield {chanpath} \ 
            Ek              -0.075 \
            Ik              0  \
            Xpower          1
        
        setfield {chanpath} \
            Gbar 270 \
            Gk              0 

        
        // No Q10 temperature adjustment found
        float temp_adj_n = 1
    

        float tab_divs = 3000
        float v_min = -0.1

        float v_max = 0.1

        float v, dv, i
            
        // Creating table for gate n, using name X for it here

        float dv = ({v_max} - {v_min})/{tab_divs}
            
        call {chanpath} TABCREATE X {tab_divs} {v_min} {v_max}
                
        v = {v_min}

            

        for (i = 0; i <= ({tab_divs}); i = i + 1)
            
            // Looking at rate: alpha
                

            float alpha
                
                        
            // Found a generic form of rate equation for alpha, using expression: (v + 0.0392) < 1e-6 && (-v-0.0392) < 1e-6? 79.4679 : ((-1.0 * 627.2) + (-1.0 * 16000 * v))/(-1.0 + (exp (-1.0 * (v + 0.0392)/ 0.005)))
            // Will translate this for GENESIS compatibility...
                    

            if ({v + 0.0392} < 1e-6 && {-v-0.0392} < 1e-6)
                alpha =  79.4679 
            else
                alpha =  {{-1.0 * 627.2} + {-1.0 * 16000 * v}}/{-1.0 + {exp {-1.0 * {v + 0.0392}/ 0.005}}}
            end
        
            
            // Looking at rate: beta
                

            float beta
                
                        
            // Found a generic form of rate equation for beta, using expression: 250.0 /(exp ((v + 0.0543)/ 0.04))
            // Will translate this for GENESIS compatibility...
                    beta = 250.0 /{exp {{v + 0.0543}/ 0.04}}
            

            // Using the alpha and beta expressions to populate the tables

            float tau = 1/(temp_adj_n * (alpha + beta))
            
            setfield {chanpath} X_A->table[{i}] {temp_adj_n * alpha}
            setfield {chanpath} X_B->table[{i}] {temp_adj_n * (alpha + beta)}
                    
            v = v + dv

        end // end of for (i = 0; i <= ({tab_divs}); i = i + 1)
            
        setfield {chanpath} X_A->calc_mode 1 X_B->calc_mode 1
                    


end

