

// **************************************************
// File generated by: neuroConstruct v1.7.0 
// **************************************************

// This file holds the implementation in GENESIS of the Cell Mechanism:
// Piriform_KA_ChannelML (Type: Channel mechanism, Model: ChannelML based process)

// with parameters: 
// /channelml/@units = SI Units 
// /channelml/notes = A channel from M. C. Vanier and J. M. Bower (1999) A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neural Models 
// /channelml/channel_type/@name = Piriform_KA_ChannelML 
// /channelml/channel_type/status/@value = stable 
// /channelml/channel_type/status/comment = Equations converted to ChannelML from GENESIS originals 16/01/13 
// /channelml/channel_type/status/contributor/name = Simon O'Connor 
// /channelml/channel_type/notes = A-type K channel, with rate equations expressed in tau and inf form 
// /channelml/channel_type/modelTranslator/name = Simon O'Connor 
// /channelml/channel_type/modelTranslator/institution = Cardiff University 
// /channelml/channel_type/modelTranslator/email = simon.oconnor - at - btinternet.com 
// /channelml/channel_type/publication/fullTitle = M. C. Vanier and J. M. Bower (1999) A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neural Models. Journal of Computat ... 
// /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=10515252&amp;dopt=Abstract 
// /channelml/channel_type/neuronDBref/modelName = K channels 
// /channelml/channel_type/neuronDBref/uri = http://senselab.med.yale.edu/senselab/NeuronDB/channelGene2.htm#table3 
// /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
// /channelml/channel_type/current_voltage_relation/@ion = k 
// /channelml/channel_type/current_voltage_relation/@default_gmax = 200 
// /channelml/channel_type/current_voltage_relation/@default_erev = -0.075 
// /channelml/channel_type/current_voltage_relation/gate[1]/@name = m 
// /channelml/channel_type/current_voltage_relation/gate[1]/@instances = 3 
// /channelml/channel_type/current_voltage_relation/gate[1]/closed_state/@id = m0 
// /channelml/channel_type/current_voltage_relation/gate[1]/open_state/@id = m 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@name = alpha 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@from = m0 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@to = m 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@expr_form = generic 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@expr = 500.0 / (exp (-1.0 * (v + 0.0393)/ 0.0308 )) 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@name = beta 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@from = m 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@to = m0 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@expr_form = generic 
// /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@expr = 500.0 /  (exp ((v + 0.0393)/ 0.0308)) 
// /channelml/channel_type/current_voltage_relation/gate[2]/@name = h 
// /channelml/channel_type/current_voltage_relation/gate[2]/@instances = 1 
// /channelml/channel_type/current_voltage_relation/gate[2]/closed_state/@id = h0 
// /channelml/channel_type/current_voltage_relation/gate[2]/open_state/@id = h 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[1]/@name = alpha 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[1]/@from = h0 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[1]/@to = h 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[1]/@expr_form = generic 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[1]/@expr = 40.0 /(exp ((v + 0.0657)/0.00762)) 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[2]/@name = beta 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[2]/@from = h 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[2]/@to = h0 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[2]/@expr_form = generic 
// /channelml/channel_type/current_voltage_relation/gate[2]/transition[2]/@expr = 40.0 /(exp (-1.0 * (v + 0.0657)/ 0.0686)) 
// /channelml/channel_type/impl_prefs/table_settings/@max_v = 0.1 
// /channelml/channel_type/impl_prefs/table_settings/@min_v = -0.1 
// /channelml/channel_type/impl_prefs/table_settings/@table_divisions = 3000 

// File from which this was generated: /home/Simon/PiriformCortexPyramidalNeuron/neuroConstruct/cellMechanisms/Piriform_KA_ChannelML/KA_Channel.xml

// XSL file with mapping to simulator: /home/Simon/PiriformCortexPyramidalNeuron/neuroConstruct/cellMechanisms/Piriform_KA_ChannelML/ChannelML_v1.8.1_GENESIStab.xsl



// This is a GENESIS script file generated from a ChannelML v1.8.1 file
// The ChannelML file is mapped onto a tabchannel object


// Units of ChannelML file: SI Units, units of GENESIS file generated: SI Units

/*
    A channel from M. C. Vanier and J. M. Bower (1999) A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neural Models
*/

function make_Piriform_KA_ChannelML

        /*
            A-type K channel, with rate equations expressed in tau and inf form

            
Reference: M. C. Vanier and J. M. Bower (1999) A Comparative Survey of Automated Parameter-Searching Methods for Compartmental Neural Models. Journal of Computational Neuroscience 7, 149-171.
            Pubmed: http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=PubMed&list_uids=10515252&dopt=Abstract

        */
        

        str chanpath = "/library/Piriform_KA_ChannelML"

        if ({exists {chanpath}})
            return
        end
        
        create tabchannel {chanpath}
            

        setfield {chanpath} \ 
            Ek              -0.075 \
            Ik              0  \
            Xpower          3 \
            Ypower          1
        
        setfield {chanpath} \
            Gbar 200 \
            Gk              0 

        
        // No Q10 temperature adjustment found
        float temp_adj_m = 1
        float temp_adj_h = 1
    

        float tab_divs = 3000
        float v_min = -0.1

        float v_max = 0.1

        float v, dv, i
            
        // Creating table for gate m, using name X for it here

        float dv = ({v_max} - {v_min})/{tab_divs}
            
        call {chanpath} TABCREATE X {tab_divs} {v_min} {v_max}
                
        v = {v_min}

            

        for (i = 0; i <= ({tab_divs}); i = i + 1)
            
            // Looking at rate: alpha
                

            float alpha
                
                        
            // Found a generic form of rate equation for alpha, using expression: 500.0 / (exp (-1.0 * (v + 0.0393)/ 0.0308 ))
            // Will translate this for GENESIS compatibility...
                    alpha = 500.0 / {exp {-1.0 * {v + 0.0393}/ 0.0308 }}
            
            // Looking at rate: beta
                

            float beta
                
                        
            // Found a generic form of rate equation for beta, using expression: 500.0 /  (exp ((v + 0.0393)/ 0.0308))
            // Will translate this for GENESIS compatibility...
                    beta = 500.0 /  {exp {{v + 0.0393}/ 0.0308}}
            

            // Using the alpha and beta expressions to populate the tables

            float tau = 1/(temp_adj_m * (alpha + beta))
            
            setfield {chanpath} X_A->table[{i}] {temp_adj_m * alpha}
            setfield {chanpath} X_B->table[{i}] {temp_adj_m * (alpha + beta)}
                    
            v = v + dv

        end // end of for (i = 0; i <= ({tab_divs}); i = i + 1)
            
        setfield {chanpath} X_A->calc_mode 1 X_B->calc_mode 1
                    
        // Creating table for gate h, using name Y for it here

        float dv = ({v_max} - {v_min})/{tab_divs}
            
        call {chanpath} TABCREATE Y {tab_divs} {v_min} {v_max}
                
        v = {v_min}

            

        for (i = 0; i <= ({tab_divs}); i = i + 1)
            
            // Looking at rate: alpha
                

            float alpha
                
                        
            // Found a generic form of rate equation for alpha, using expression: 40.0 /(exp ((v + 0.0657)/0.00762))
            // Will translate this for GENESIS compatibility...
                    alpha = 40.0 /{exp {{v + 0.0657}/0.00762}}
            
            // Looking at rate: beta
                

            float beta
                
                        
            // Found a generic form of rate equation for beta, using expression: 40.0 /(exp (-1.0 * (v + 0.0657)/ 0.0686))
            // Will translate this for GENESIS compatibility...
                    beta = 40.0 /{exp {-1.0 * {v + 0.0657}/ 0.0686}}
            

            // Using the alpha and beta expressions to populate the tables

            float tau = 1/(temp_adj_h * (alpha + beta))
            
            setfield {chanpath} Y_A->table[{i}] {temp_adj_h * alpha}
            setfield {chanpath} Y_B->table[{i}] {temp_adj_h * (alpha + beta)}
                    
            v = v + dv

        end // end of for (i = 0; i <= ({tab_divs}); i = i + 1)
            
        setfield {chanpath} Y_A->calc_mode 1 Y_B->calc_mode 1
                    


end

