
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.7.0
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 0.583  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.0436   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]

*set_global	         EREST_ACT	-0.0743  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
// Cell mechanism: Ca_buffer_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: Kahp1_ChannelML (density: 4.0E-9 mS um^-2)
// Cell mechanism: Olfactory_Ca_ChannelML (density: 1.0E-8 mS um^-2)
*set_compt_param     ELEAK -0.0743  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 0.05030004  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*double_endpoint
Soma none 0 0 0 0 21.3 0 10.4 Ca_buffer_ChannelML 1 Kahp1_ChannelML 4 Olfactory_Ca_ChannelML 10 
*double_endpoint_off

