
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.6.1
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 0.583  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.0436   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]

*set_global	         EREST_ACT	-0.06  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
// Cell mechanism: KDR_Hipo_original (density: 2.7E-7 mS um^-2)
// Cell mechanism: Na_Hipo_original (density: 2.8E-6 mS um^-2)
// Cell mechanism: Piriform_KA_original (density: 2.0E-7 mS um^-2)
*set_compt_param     ELEAK -0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 0.05030004  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*double_endpoint
Soma none 0 0 0 0 21.3 0 10.4 KDR_Hipo_original 270 Na_Hipo_original 2800 Piriform_KA_original 200 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
*double_endpoint
B1__Extra_0 Soma 0 0 0 0 -23.91 0 3.2 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1__Extra_1 B1__Extra_0 0 -47.82 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1__Extra_2 B1__Extra_1 0 -71.73 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1__Extra_3 B1__Extra_2 0 -95.64001 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1__Extra_4 B1__Extra_3 0 -119.55 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1__Extra_5 B1__Extra_4 0 -143.46 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1__Extra_6 B1__Extra_5 0 -167.37 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1__Extra_7 B1__Extra_6 0 -191.28 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1__Extra_8 B1__Extra_7 0 -215.19 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B1 B1__Extra_8 0 -239.1 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_0 B1 0 -263.01 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_1 B2__Extra_0 0 -286.92 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_2 B2__Extra_1 0 -310.83 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_3 B2__Extra_2 0 -334.74 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_4 B2__Extra_3 0 -358.65 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_5 B2__Extra_4 0 -382.56 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_6 B2__Extra_5 0 -406.47 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_7 B2__Extra_6 0 -430.38 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2__Extra_8 B2__Extra_7 0 -454.29 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
B2 B2__Extra_8 0 -478.2 0 3.2 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_0 Soma 0 39.11539 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_1 D1b1__Extra_0 0 56.93078 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_2 D1b1__Extra_1 0 74.74616 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_3 D1b1__Extra_2 0 92.56155 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_4 D1b1__Extra_3 0 110.3769 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_5 D1b1__Extra_4 0 128.1923 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_6 D1b1__Extra_5 0 146.0077 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_7 D1b1__Extra_6 0 163.8231 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_8 D1b1__Extra_7 0 181.6385 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_9 D1b1__Extra_8 0 199.4539 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_10 D1b1__Extra_9 0 217.2693 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1__Extra_11 D1b1__Extra_10 0 235.0847 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b1 D1b1__Extra_11 0 252.9 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_0 D1b1 0 270.7154 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_1 D1b2__Extra_0 0 288.5308 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_2 D1b2__Extra_1 0 306.3462 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_3 D1b2__Extra_2 0 324.1616 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_4 D1b2__Extra_3 0 341.977 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_5 D1b2__Extra_4 0 359.7924 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_6 D1b2__Extra_5 0 377.6078 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_7 D1b2__Extra_6 0 395.4232 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_8 D1b2__Extra_7 0 413.2385 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_9 D1b2__Extra_8 0 431.0539 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_10 D1b2__Extra_9 0 448.8693 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2__Extra_11 D1b2__Extra_10 0 466.6847 0 1.6 

// Cell mechanism: LeakConductance (density: 1.98807E-8 mS um^-2)
D1b2 D1b2__Extra_11 0 484.5001 0 1.6 

