#! /usr/bin/env python

#
# make_odor_shock_rate_modulation: make odor response file.
#

import sys, string
from math import pi, sin, ceil

assert len(sys.argv) == 4

filename = sys.argv[1]
minrate  = string.atof(sys.argv[2])
maxtime  = string.atof(sys.argv[3])

file = open(filename, "w")

ntypes  = 1    # Types of odor responses.
ntimes  = ceil(1000 * maxtime)
dt      = maxtime / ntimes

t = 0.0

file.write("%8d\t%8d\t%8.6f\n" % (ntypes, ntimes, maxtime))

assert minrate >= 0.0

#
# After a shock stimulus, the background firing rate drops to
# minrate and then climbs back to the normal rate.  It reaches
# the normal rate at maxtime.
#

while t < maxtime:
    val1 = minrate + (1.0 - minrate) * t / maxtime
    file.write("%8.6f\n" % val1)
    t = t + dt

file.close()


